config/routes.rb
Crawl::Application.routes.draw do
  root :to => "home#index"
  
  # get "/pub_crawls" => "pub_crawls#new"

  resources :stops
  resources :locations
  resources :pub_crawls

end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :stop
end

app/models/pub_crawl.rb
class PubCrawl < ActiveRecord::Base
	has_many :stops
end

app/models/route.rb
class Route < ActiveRecord::Base
	has_many :stops
end

app/models/stop.rb
class Stop < ActiveRecord::Base
	has_many :locations
	belongs_to :pub_crawl
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
  	@stop_spot = Stop.all
  end

  def show
  	@locale = Location.find(params[:id])
  end

  
end

app/controllers/pub_crawls_controller.rb
class PubCrawlsController < ApplicationController
  
  attr_accessor :route

  def index
     
  end

  def show
    @crawl = PubCrawl.find(params[:id])
  end

  def new
    @crawl = PubCrawl.new
  end

  def create
    @crawl = PubCrawl.new(crawl_params)
    @crawl.save
    redirect_to pub_crawls_path
  end

  private
  def crawl_params
    params.require(:pub_crawl).permit(:stop_one, :stop_two, :stop_three, :name)
  end

end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  def index
  	@stop_spot = Stop.all
  end
  def show
  	@stop = Stop.find(params[:id])
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
</br>
</br>
</br>

  <div class="col-lg-12 text-center">
    <%= image_tag "pub-crawl.jpg" %>
  </div>

  <div class="col-lg-12 text-center">
    <h2>PUB CRAWLERS</h2>
  </br>
    <p>Crawl your way through Austin's best PUBs!</p>
    <p>Use PUBlic transit - no need to drive.</p>
    <h3><%= link_to 'Create your own PUB crawl', new_pub_crawl_path %></h3>
    <h3><%= link_to '...or see crawls already done.', pub_crawls_path %></h3>
  </div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Twitter Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header nav-justified">

      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <%= link_to 'Stops', stops_path, class: 'navbar-brand' %>
      <%= link_to 'Locations', locations_path, class: 'navbar-brand' %>
      <%= link_to 'Create a Crawl!', new_pub_crawl_path, class: 'navbar-brand' %>

    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Crawl" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Crawl" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/locations/index.html.erb
</br>
</br>
</br>

<img class="locale" src="http://publichousegarage.com/wp-content/uploads/2013/08/cocktail-final.jpg">

<% @stop_spot.each do |spot| %>
<h2><%= spot.name %></h2>
<p>
	<% locale = Location.all %>
	<% locale.find_all_by_stop_id(spot.id).each do |locale| %>
	<p><%= link_to locale.name, location_path(locale[:id]) %></p>
	<% end %>
</p>
<% end %>

app/views/locations/show.html.erb
</br>
</br>



<h2><%= @locale.name %></h2>
<h4><%= @locale.address %></h4>
<h4><%= @locale.phone %></h4>
<a href="<%= @locale.website %>"><img class = "locale" src= "<%= @locale.image %>"></a>

<p><%= link_to 'Back to all locations', locations_path %> - <%= link_to 'home', root_path %></p>

app/views/pub_crawls/_form.html.erb
</br>
</br>

<p><%= form_for @crawl do |f| %></p>
	<p>	<%= f.label :name %> <%= f.text_field :name, :placeholder => 'Name your crawl'%></p>
	<p><%= f.label :stop_one %>
	<%= f.collection_select :stop_one, Stop.all, :name, :name %></p>	
	<p><%= f.label :stop_two %>
	<%= f.collection_select :stop_two, Stop.all, :name, :name %></p>
	<p><%= f.label :stop_three %>
	<%= f.collection_select :stop_three, Stop.all, :name, :name %></p>
	<p><%= f.submit %></p>

<p><% end %></p>

app/views/pub_crawls/index.html.erb
<h1>Check out all the crawls!</h1>
<% crawl = PubCrawl.all %>
<% crawl.each do |pc| %>
	<h3><%= link_to pc.name, pc %></h3>
	<% stop_1 = Stop.find_by_name pc.stop_one %>
	<% stop_2 = Stop.find_by_name pc.stop_two %>	
	<% stop_3 = Stop.find_by_name pc.stop_three %>

	First stop: <%= link_to pc.stop_one, stop_path(stop_1[:id]) %></br>
	Second stop: <%= link_to pc.stop_two, stop_path(stop_2[:id]) %></br>
	Finish line: <%= link_to pc.stop_three, stop_path(stop_3[:id]) %></br>
<% end %>

app/views/pub_crawls/new.html.erb
</br>
</br>
</br>
</br>

<img src="http://crawltheglobe.com/wp-content/uploads/2012/04/guided-pub-crawl.jpg">

</br>

<h2>Chose your Crawl!</h2>

<%= render "form" %>

</br>
</br>

app/views/pub_crawls/show.html.erb
</br>
</br>
<h2>This is your crawl:</h2>
<h3><%= @crawl.name %></h2>

	First stop: <%= @crawl.stop_one %></br>
	Second stop: <%= @crawl.stop_two %></br>
	Finish line: <%= @crawl.stop_three %></br></br>

<p><%= link_to 'All Crawls', pub_crawls_path %> - <%= link_to 'home', root_path %></p>

app/views/stops/index.html.erb
</br>
</br>
</br>

<img class="locale" src ="http://i655.photobucket.com/albums/uu271/yfrimer/s-is-for-stop-sign-maze.png">

<% stop_spot = Stop.all %>
<% stop_spot.each do |spot| %>

<h3><%= link_to spot.name, stop_path(spot[:id]) %></h3>
<% end %>
<img class= "stops_map" src="http://maps.googleapis.com/maps/api/staticmap?center=Austin,Texas,TX&zoom=12.5&size=800x1000&scale=2&maptype=roadmap
&markers=color:blue%7Clabel:Burnet%7C30.318126,-97.739952&markers=color:orange%7Clabel:University%7C30.296804,-97.742028
&markers=color:red%7Ccolor:red%7Clabel:Downtown%7C30.265404,-97.74396&markers=color:green%7Clabel:SoCo%7C30.248071,-97.750404&sensor=false"/>

app/views/stops/show.html.erb
</br>
</br>
</br>

<h1><%= @stop.name %> </h1>
<% @stop.locations.each do |locale| %>
<p><%= link_to locale.name, location_path(locale[:id]) %></p>
<% end %>
<img src='http://maps.googleapis.com/maps/api/staticmap?center=<%= @stop.latitude %>,<%= @stop.longitude %>&zoom=15&size=1000x500&maptype=roadmap&markers=color:<%= @stop.color %>%7Clabel:B%7C<%= @stop.latitude %>,<%= @stop.longitude %>&sensor=false'>

<p><%= link_to 'Back to all Stops', stops_path %> - <%= link_to 'home', root_path %></p>